<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE ITSO_HOPS_to_POST_File [<!ELEMENT ITSO_HOPS_to_POST_File (ITSO_Message_Header, ITSO_Message_Frame)>
<!ELEMENT ITSO_Message_Header (ITSO_Message_Version, ITSO_Message_Class)>
<!ELEMENT ITSO_Message_Frame (ITSO_Batch_Header, ITSO_Message_Body)>
<!ELEMENT ITSO_Batch_Header (ITSO_Message_CRC, ITSO_Originator, ITSO_Recipient,(ITSO_Recipient_Type | (ITSO_Recipient_Type, ITSO_Group_Message_Seq_Num,ITSO_ISAM_Message_Seq_Num))?)>
<!ELEMENT ITSO_Message_Body (ITSO_Data_Frame | ITSO_Secure_Data_Frame)+>
<!ELEMENT ITSO_Data_Frame (ITSO_Message_Code, ITSO_DTS, ITSO_Data_Block, ITSO_DF_Trailer)>
<!ELEMENT ITSO_Data_Block (ITSO_DB_Len, ITSO_Num_Data_Elements, ITSO_Dest_Count, ITSO_Destination, ITSO_Data)>
<!ELEMENT ITSO_DF_Trailer (ITSO_Trailer_Length, ITSO_KID, ITSO_SealerID, ITSO_Seq_Num, ITSO_Seal)>
<!ELEMENT ITSO_Data (#PCDATA)>
<!ELEMENT ITSO_DB_Len (#PCDATA)>
<!ELEMENT ITSO_Dest_Count (#PCDATA)>
<!ELEMENT ITSO_Destination (#PCDATA)>
<!ELEMENT ITSO_DTS (#PCDATA)>
<!ELEMENT ITSO_KID (#PCDATA)>
<!ELEMENT ITSO_Message_Class (#PCDATA)>
<!ELEMENT ITSO_Message_Code (#PCDATA)>
<!ELEMENT ITSO_Message_CRC (#PCDATA)>
<!ELEMENT ITSO_Message_Version (#PCDATA)>
<!ELEMENT ITSO_Num_Data_Elements (#PCDATA)>
<!ELEMENT ITSO_Originator (#PCDATA)>
<!ELEMENT ITSO_Recipient (#PCDATA)>
<!ELEMENT ITSO_Recipient_Type (#PCDATA)>
<!ELEMENT ITSO_Group_Message_Seq_Num (#PCDATA)>
<!ELEMENT ITSO_ISAM_Message_Seq_Num (#PCDATA)>
<!ELEMENT ITSO_SDF (#PCDATA)>
<!ELEMENT ITSO_Seal (#PCDATA)>
<!ELEMENT ITSO_SealerID (#PCDATA)>
<!ELEMENT ITSO_Secure_Data_Frame (ITSO_SDF)>
<!ELEMENT ITSO_Seq_Num (#PCDATA)>
<!ELEMENT ITSO_Trailer_Length (#PCDATA)>]>
<ITSO_HOPS_to_POST_File>
<ITSO_Message_Header>
<ITSO_Message_Version>3</ITSO_Message_Version>
<ITSO_Message_Class>2</ITSO_Message_Class>
</ITSO_Message_Header>
<ITSO_Message_Frame>
<ITSO_Batch_Header>
<ITSO_Message_CRC>6A32</ITSO_Message_CRC>
<ITSO_Originator>6335970060004E</ITSO_Originator>
<ITSO_Recipient>63359700580001</ITSO_Recipient>
<ITSO_Recipient_Type>00</ITSO_Recipient_Type>
</ITSO_Batch_Header>
<ITSO_Message_Body>
<ITSO_Data_Frame>
<ITSO_Message_Code>0603</ITSO_Message_Code>
<ITSO_DTS>635395</ITSO_DTS>
<ITSO_Data_Block>
<ITSO_DB_Len>0000016F14</ITSO_DB_Len>

<ITSO_Num_Data_Elements>00</ITSO_Num_Data_Elements>
<ITSO_Dest_Count>01</ITSO_Dest_Count>
<ITSO_Destination>63359700580001</ITSO_Destination>
<ITSO_Data>00000F0101004707A12009000C0202040100230601001100010101004707A12019000C0202040100230601001100010101004707A12029000C0202040100230601001100010101004707A12039000C0202040100230601001100010101004707A12049000C0202040100230601001100010101004707A12059000C0202040100230601001100010101004707A12069000C0202040100230601001100010101004707A12079000C0202040100230601001100010101004707A12089000C0202040100230601001100010101004707A12099000C0202040100230601001100010101004707A120A9000C0202040100230601001100010101004707A120B9000C0202040100230601001100010101004707A120C9000C0202040100230601001100010101004707A120D9000C0202040100230601001100010101004707A120E9000C0202040100230601001100011111222233334444555566667777888899990000</ITSO_Data>
</ITSO_Data_Block>
<ITSO_DF_Trailer>
<ITSO_Trailer_Length>14</ITSO_Trailer_Length>
<ITSO_KID>50</ITSO_KID>
<ITSO_SealerID>63359700600046</ITSO_SealerID>
<ITSO_Seq_Num>00002F</ITSO_Seq_Num>
<ITSO_Seal>5EA15EA15EA15EA1</ITSO_Seal>
</ITSO_DF_Trailer>
</ITSO_Data_Frame>
<ITSO_Data_Frame>
<ITSO_Message_Code>0603</ITSO_Message_Code>
<ITSO_DTS>635395</ITSO_DTS>
<ITSO_Data_Block>
<ITSO_DB_Len>0000016F14</ITSO_DB_Len>

<ITSO_Num_Data_Elements>00</ITSO_Num_Data_Elements>
<ITSO_Dest_Count>01</ITSO_Dest_Count>
<ITSO_Destination>63359700580001</ITSO_Destination>
<ITSO_Data>00000F0101004707A120F9000C0202040100230601001100010101004707A12109000C0202040100230601001100010101004707A12119000C0202040100230601001100010101004707A12129000C0202040100230601001100010101004707A12139000C0202040100230601001100010101004707A12149000C0202040100230601001100010101004707A12159000C0202040100230601001100010101004707A12169000C0202040100230601001100010101004707A12179000C0202040100230601001100010101004707A12189000C0202040100230601001100010101004707A12199000C0202040100230601001100010101004707A121A9000C0202040100230601001100010101004707A121B9000C0202040100230601001100010101004707A121C9000C0202040100230601001100010101004707A121D9000C0202040100230601001100011111222233334444555566667777888899990000</ITSO_Data>
</ITSO_Data_Block>
<ITSO_DF_Trailer>
<ITSO_Trailer_Length>14</ITSO_Trailer_Length>
<ITSO_KID>50</ITSO_KID>
<ITSO_SealerID>63359700600046</ITSO_SealerID>
<ITSO_Seq_Num>00002F</ITSO_Seq_Num>
<ITSO_Seal>5EA15EA15EA15EA1</ITSO_Seal>
</ITSO_DF_Trailer>
</ITSO_Data_Frame>
<ITSO_Data_Frame>
<ITSO_Message_Code>0603</ITSO_Message_Code>
<ITSO_DTS>635395</ITSO_DTS>
<ITSO_Data_Block>
<ITSO_DB_Len>0000016F14</ITSO_DB_Len>

<ITSO_Num_Data_Elements>00</ITSO_Num_Data_Elements>
<ITSO_Dest_Count>01</ITSO_Dest_Count>
<ITSO_Destination>63359700580001</ITSO_Destination>
<ITSO_Data>00000F0101004707A121E9000C0202040100230601001100010101004707A121F9000C0202040100230601001100010101004707A12209000C0202040100230601001100010101004707A12219000C0202040100230601001100010101004707A12229000C0202040100230601001100010101004707A12239000C0202040100230601001100010101004707A12249000C0202040100230601001100010101004707A12259000C0202040100230601001100010101004707A12269000C0202040100230601001100010101004707A12279000C0202040100230601001100010101004707A12289000C0202040100230601001100010101004707A12299000C0202040100230601001100010101004707A122A9000C0202040100230601001100010101004707A122B9000C0202040100230601001100010101004707A122C9000C0202040100230601001100011111222233334444555566667777888899990000</ITSO_Data>
</ITSO_Data_Block>
<ITSO_DF_Trailer>
<ITSO_Trailer_Length>14</ITSO_Trailer_Length>
<ITSO_KID>50</ITSO_KID>
<ITSO_SealerID>63359700600046</ITSO_SealerID>
<ITSO_Seq_Num>00002F</ITSO_Seq_Num>
<ITSO_Seal>5EA15EA15EA15EA1</ITSO_Seal>
</ITSO_DF_Trailer>
</ITSO_Data_Frame>
</ITSO_Message_Body>
</ITSO_Message_Frame>
</ITSO_HOPS_to_POST_File>
